name: RivalCore
main: me.rival.dev.Main
version: 1.0-FINAL
author: Rival Development
commands:
  ads:
    aliases: [adban]
  gg:
    alisases: [ggwave]
  donation:
    aliases: [donate]
  help:
    aliases: [help]
  meteor:
    alises: [meteors]