name: RivalCore
main: me.rival.dev.Main
version: 1.0-FINAL
authors: [Rival Development, Strokkur24]
depend:
  - PlaceholderAPI
  - Vault
commands:
  ads:
    aliases: [adban]
  gg:
    alisases: [ggwave]
  donation:
    aliases: [donate]
  help:
    aliases: [help]
  meteor:
    alises: [meteors]